### PR TITLE
Feat/bump stackage resolver

### PR DESCRIPTION
**Pull request by thomasbach-dev**
With this we update to GHC 8.10.7. As described in the latest commit, I reran code generation for the `example` directory and golden tests. Everything was stable. So I guess we should be good here. :)

### CODE REVIEW

**Comment by NorfairKing** [comment]
It's important to update the nixpkgs version then too.
You should use `lts-18.16` and `nix-shell --command 'niv update nixpkgs --branch nixos-21.11'`

**Comment by thomasbach-dev** [comment]
Cool, I already wanted to open a ticket requesting for a version bump in the nix machinery. I'll adapt things.

@NorfairKing What's the motive behind using 18.16? Is it because nix is pinned to this?

**Comment by NorfairKing** [comment]
> Is it because nix is pinned to this?

Yup.

**Comment by joelfisch** [comment]
This looks good to me :+1: 

The bump on the generated stack.yaml is correct as well. We could drop it as I think it is not very useful in practice. Currently, it is used for the tests so I would leave it for now as it is not really a pain-point as far as I am concerned. Please correct me if it is for you.

**Pull request merged**
